//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAVSCMIntegrator.SCMCustomersSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SCMCustomers_Binding", Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public partial class SCMCustomers_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
               
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SCMCustomers")]
        public SCMCustomers Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((SCMCustomers)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SCMCustomers")]
        public SCMCustomers ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((SCMCustomers)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SCMCustomers[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] SCMCustomers_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((SCMCustomers[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SCMCustomers_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SCMCustomers_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref SCMCustomers SCMCustomers) {
            object[] results = this.Invoke("Create", new object[] {
                        SCMCustomers});
            SCMCustomers = ((SCMCustomers)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(SCMCustomers SCMCustomers) {
            this.CreateAsync(SCMCustomers, null);
        }
        
        /// <remarks/>
        public void CreateAsync(SCMCustomers SCMCustomers, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        SCMCustomers}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref SCMCustomers[] SCMCustomers_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        SCMCustomers_List});
            SCMCustomers_List = ((SCMCustomers[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(SCMCustomers[] SCMCustomers_List) {
            this.CreateMultipleAsync(SCMCustomers_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(SCMCustomers[] SCMCustomers_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        SCMCustomers_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref SCMCustomers SCMCustomers) {
            object[] results = this.Invoke("Update", new object[] {
                        SCMCustomers});
            SCMCustomers = ((SCMCustomers)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(SCMCustomers SCMCustomers) {
            this.UpdateAsync(SCMCustomers, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(SCMCustomers SCMCustomers, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        SCMCustomers}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref SCMCustomers[] SCMCustomers_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        SCMCustomers_List});
            SCMCustomers_List = ((SCMCustomers[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SCMCustomers[] SCMCustomers_List) {
            this.UpdateMultipleAsync(SCMCustomers_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SCMCustomers[] SCMCustomers_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        SCMCustomers_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scmcustomers:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scmcustomers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public partial class SCMCustomers {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string primary_Contact_NoField;
        
        private string contactField;
        
        private string area_Sales_ManagerField;
        
        private string area_Sales_RepField;
        
        private string accounts_DeveloperField;
        
        private string retail_Area_ManagerField;
        
        private string search_NameField;
        
        private decimal balance_LCYField;
        
        private bool balance_LCYFieldSpecified;
        
        private Credit_Rating credit_RatingField;
        
        private bool credit_RatingFieldSpecified;
        
        private decimal credit_Limit_LCYField;
        
        private bool credit_Limit_LCYFieldSpecified;
        
        private string salesperson_CodeField;
        
        private string responsibility_CenterField;
        
        private string service_Zone_CodeField;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string vAT_Exempt_CertNoField;
        
        private bool route_Sales_CustomerField;
        
        private bool route_Sales_CustomerFieldSpecified;
        
        private bool bad_Debtor_StatusField;
        
        private bool bad_Debtor_StatusFieldSpecified;
        
        private Legal_Status legal_StatusField;
        
        private bool legal_StatusFieldSpecified;
        
        private string customer_PINField;
        
        private Customer_Type customer_TypeField;
        
        private bool customer_TypeFieldSpecified;
        
        private string distributorField;
        
        private string transport_RouteField;
        
        private bool key_AccountField;
        
        private bool key_AccountFieldSpecified;
        
        private bool excise_DutyField;
        
        private bool excise_DutyFieldSpecified;
        
        private decimal rPM_RateField;
        
        private bool rPM_RateFieldSpecified;
        
        private string sales_AreaField;
        
        private string sales_ClusterField;
        
        private string old_Customer_NoField;
        
        private string fax_NoField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string iC_Partner_CodeField;
        
        private string bill_to_Customer_NoField;
        
        private int invoice_CopiesField;
        
        private bool invoice_CopiesFieldSpecified;
        
        private string invoice_Disc_CodeField;
        
        private Copy_Sell_to_Addr_to_Qte_From copy_Sell_to_Addr_to_Qte_FromField;
        
        private bool copy_Sell_to_Addr_to_Qte_FromFieldSpecified;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string customer_Posting_GroupField;
        
        private string customer_Price_GroupField;
        
        private string customer_Disc_GroupField;
        
        private bool allow_Line_DiscField;
        
        private bool allow_Line_DiscFieldSpecified;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private decimal prepayment_PercentField;
        
        private bool prepayment_PercentFieldSpecified;
        
        private Application_Method application_MethodField;
        
        private bool application_MethodFieldSpecified;
        
        private Partner_Type partner_TypeField;
        
        private bool partner_TypeFieldSpecified;
        
        private string payment_Terms_CodeField;
        
        private string payment_Method_CodeField;
        
        private string reminder_Terms_CodeField;
        
        private string fin_Charge_Terms_CodeField;
        
        private string cash_Flow_Payment_Terms_CodeField;
        
        private bool print_StatementsField;
        
        private bool print_StatementsFieldSpecified;
        
        private int last_Statement_NoField;
        
        private bool last_Statement_NoFieldSpecified;
        
        private bool block_Payment_ToleranceField;
        
        private bool block_Payment_ToleranceFieldSpecified;
        
        private string preferred_Bank_AccountField;
        
        private Delivery_Method delivery_MethodField;
        
        private bool delivery_MethodFieldSpecified;
        
        private string location_CodeField;
        
        private decimal distance_from_Plant_KMField;
        
        private bool distance_from_Plant_KMFieldSpecified;
        
        private string gPS_CoordinatesField;
        
        private bool combine_ShipmentsField;
        
        private bool combine_ShipmentsFieldSpecified;
        
        private Reserve reserveField;
        
        private bool reserveFieldSpecified;
        
        private Shipping_Advice shipping_AdviceField;
        
        private bool shipping_AdviceFieldSpecified;
        
        private string shipment_Method_CodeField;
        
        private string shipping_Agent_CodeField;
        
        private string shipping_Agent_Service_CodeField;
        
        private string shipping_TimeField;
        
        private string base_Calendar_CodeField;
        
        private string customized_CalendarField;
        
        private decimal standard_Set_TimeField;
        
        private bool standard_Set_TimeFieldSpecified;
        
        private string sales_RegionField;
        
        private string currency_CodeField;
        
        private string language_CodeField;
        
        private string vAT_Registration_NoField;
        
        private string submitted_ByField;
        
        private System.DateTime submitted_DateField;
        
        private bool submitted_DateFieldSpecified;
        
        private string verified_ByField;
        
        private System.DateTime verified_DateField;
        
        private bool verified_DateFieldSpecified;
        
        private string approved_ByField;
        
        private System.DateTime approval_DateField;
        
        private bool approval_DateFieldSpecified;
        
        private string created_ByField;
        
        private System.DateTime creation_DateField;
        
        private bool creation_DateFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Primary_Contact_No {
            get {
                return this.primary_Contact_NoField;
            }
            set {
                this.primary_Contact_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Area_Sales_Manager {
            get {
                return this.area_Sales_ManagerField;
            }
            set {
                this.area_Sales_ManagerField = value;
            }
        }
        
        /// <remarks/>
        public string Area_Sales_Rep {
            get {
                return this.area_Sales_RepField;
            }
            set {
                this.area_Sales_RepField = value;
            }
        }
        
        /// <remarks/>
        public string Accounts_Developer {
            get {
                return this.accounts_DeveloperField;
            }
            set {
                this.accounts_DeveloperField = value;
            }
        }
        
        /// <remarks/>
        public string Retail_Area_Manager {
            get {
                return this.retail_Area_ManagerField;
            }
            set {
                this.retail_Area_ManagerField = value;
            }
        }
        
        /// <remarks/>
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance_LCY {
            get {
                return this.balance_LCYField;
            }
            set {
                this.balance_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_LCYSpecified {
            get {
                return this.balance_LCYFieldSpecified;
            }
            set {
                this.balance_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Credit_Rating Credit_Rating {
            get {
                return this.credit_RatingField;
            }
            set {
                this.credit_RatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_RatingSpecified {
            get {
                return this.credit_RatingFieldSpecified;
            }
            set {
                this.credit_RatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Credit_Limit_LCY {
            get {
                return this.credit_Limit_LCYField;
            }
            set {
                this.credit_Limit_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_Limit_LCYSpecified {
            get {
                return this.credit_Limit_LCYFieldSpecified;
            }
            set {
                this.credit_Limit_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        public string Service_Zone_Code {
            get {
                return this.service_Zone_CodeField;
            }
            set {
                this.service_Zone_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Blocked Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Exempt_CertNo {
            get {
                return this.vAT_Exempt_CertNoField;
            }
            set {
                this.vAT_Exempt_CertNoField = value;
            }
        }
        
        /// <remarks/>
        public bool Route_Sales_Customer {
            get {
                return this.route_Sales_CustomerField;
            }
            set {
                this.route_Sales_CustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Route_Sales_CustomerSpecified {
            get {
                return this.route_Sales_CustomerFieldSpecified;
            }
            set {
                this.route_Sales_CustomerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Bad_Debtor_Status {
            get {
                return this.bad_Debtor_StatusField;
            }
            set {
                this.bad_Debtor_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bad_Debtor_StatusSpecified {
            get {
                return this.bad_Debtor_StatusFieldSpecified;
            }
            set {
                this.bad_Debtor_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Legal_Status Legal_Status {
            get {
                return this.legal_StatusField;
            }
            set {
                this.legal_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Legal_StatusSpecified {
            get {
                return this.legal_StatusFieldSpecified;
            }
            set {
                this.legal_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Customer_PIN {
            get {
                return this.customer_PINField;
            }
            set {
                this.customer_PINField = value;
            }
        }
        
        /// <remarks/>
        public Customer_Type Customer_Type {
            get {
                return this.customer_TypeField;
            }
            set {
                this.customer_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Customer_TypeSpecified {
            get {
                return this.customer_TypeFieldSpecified;
            }
            set {
                this.customer_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Distributor {
            get {
                return this.distributorField;
            }
            set {
                this.distributorField = value;
            }
        }
        
        /// <remarks/>
        public string Transport_Route {
            get {
                return this.transport_RouteField;
            }
            set {
                this.transport_RouteField = value;
            }
        }
        
        /// <remarks/>
        public bool Key_Account {
            get {
                return this.key_AccountField;
            }
            set {
                this.key_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Key_AccountSpecified {
            get {
                return this.key_AccountFieldSpecified;
            }
            set {
                this.key_AccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Excise_Duty {
            get {
                return this.excise_DutyField;
            }
            set {
                this.excise_DutyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Excise_DutySpecified {
            get {
                return this.excise_DutyFieldSpecified;
            }
            set {
                this.excise_DutyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal RPM_Rate {
            get {
                return this.rPM_RateField;
            }
            set {
                this.rPM_RateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RPM_RateSpecified {
            get {
                return this.rPM_RateFieldSpecified;
            }
            set {
                this.rPM_RateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Area {
            get {
                return this.sales_AreaField;
            }
            set {
                this.sales_AreaField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Cluster {
            get {
                return this.sales_ClusterField;
            }
            set {
                this.sales_ClusterField = value;
            }
        }
        
        /// <remarks/>
        public string Old_Customer_No {
            get {
                return this.old_Customer_NoField;
            }
            set {
                this.old_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
            }
        }
        
        /// <remarks/>
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
            }
        }
        
        /// <remarks/>
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Customer_No {
            get {
                return this.bill_to_Customer_NoField;
            }
            set {
                this.bill_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Invoice_Copies {
            get {
                return this.invoice_CopiesField;
            }
            set {
                this.invoice_CopiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invoice_CopiesSpecified {
            get {
                return this.invoice_CopiesFieldSpecified;
            }
            set {
                this.invoice_CopiesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Disc_Code {
            get {
                return this.invoice_Disc_CodeField;
            }
            set {
                this.invoice_Disc_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Copy_Sell_to_Addr_to_Qte_From Copy_Sell_to_Addr_to_Qte_From {
            get {
                return this.copy_Sell_to_Addr_to_Qte_FromField;
            }
            set {
                this.copy_Sell_to_Addr_to_Qte_FromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Sell_to_Addr_to_Qte_FromSpecified {
            get {
                return this.copy_Sell_to_Addr_to_Qte_FromFieldSpecified;
            }
            set {
                this.copy_Sell_to_Addr_to_Qte_FromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Posting_Group {
            get {
                return this.customer_Posting_GroupField;
            }
            set {
                this.customer_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Price_Group {
            get {
                return this.customer_Price_GroupField;
            }
            set {
                this.customer_Price_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Disc_Group {
            get {
                return this.customer_Disc_GroupField;
            }
            set {
                this.customer_Disc_GroupField = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_Line_Disc {
            get {
                return this.allow_Line_DiscField;
            }
            set {
                this.allow_Line_DiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Line_DiscSpecified {
            get {
                return this.allow_Line_DiscFieldSpecified;
            }
            set {
                this.allow_Line_DiscFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Prices_Including_VAT {
            get {
                return this.prices_Including_VATField;
            }
            set {
                this.prices_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified {
            get {
                return this.prices_Including_VATFieldSpecified;
            }
            set {
                this.prices_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepayment_Percent {
            get {
                return this.prepayment_PercentField;
            }
            set {
                this.prepayment_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepayment_PercentSpecified {
            get {
                return this.prepayment_PercentFieldSpecified;
            }
            set {
                this.prepayment_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Application_Method Application_Method {
            get {
                return this.application_MethodField;
            }
            set {
                this.application_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_MethodSpecified {
            get {
                return this.application_MethodFieldSpecified;
            }
            set {
                this.application_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Partner_Type Partner_Type {
            get {
                return this.partner_TypeField;
            }
            set {
                this.partner_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Partner_TypeSpecified {
            get {
                return this.partner_TypeFieldSpecified;
            }
            set {
                this.partner_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Method_Code {
            get {
                return this.payment_Method_CodeField;
            }
            set {
                this.payment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reminder_Terms_Code {
            get {
                return this.reminder_Terms_CodeField;
            }
            set {
                this.reminder_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Fin_Charge_Terms_Code {
            get {
                return this.fin_Charge_Terms_CodeField;
            }
            set {
                this.fin_Charge_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Cash_Flow_Payment_Terms_Code {
            get {
                return this.cash_Flow_Payment_Terms_CodeField;
            }
            set {
                this.cash_Flow_Payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Print_Statements {
            get {
                return this.print_StatementsField;
            }
            set {
                this.print_StatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Print_StatementsSpecified {
            get {
                return this.print_StatementsFieldSpecified;
            }
            set {
                this.print_StatementsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Last_Statement_No {
            get {
                return this.last_Statement_NoField;
            }
            set {
                this.last_Statement_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Statement_NoSpecified {
            get {
                return this.last_Statement_NoFieldSpecified;
            }
            set {
                this.last_Statement_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Block_Payment_Tolerance {
            get {
                return this.block_Payment_ToleranceField;
            }
            set {
                this.block_Payment_ToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Block_Payment_ToleranceSpecified {
            get {
                return this.block_Payment_ToleranceFieldSpecified;
            }
            set {
                this.block_Payment_ToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Preferred_Bank_Account {
            get {
                return this.preferred_Bank_AccountField;
            }
            set {
                this.preferred_Bank_AccountField = value;
            }
        }
        
        /// <remarks/>
        public Delivery_Method Delivery_Method {
            get {
                return this.delivery_MethodField;
            }
            set {
                this.delivery_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Delivery_MethodSpecified {
            get {
                return this.delivery_MethodFieldSpecified;
            }
            set {
                this.delivery_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Distance_from_Plant_KM {
            get {
                return this.distance_from_Plant_KMField;
            }
            set {
                this.distance_from_Plant_KMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Distance_from_Plant_KMSpecified {
            get {
                return this.distance_from_Plant_KMFieldSpecified;
            }
            set {
                this.distance_from_Plant_KMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string GPS_Coordinates {
            get {
                return this.gPS_CoordinatesField;
            }
            set {
                this.gPS_CoordinatesField = value;
            }
        }
        
        /// <remarks/>
        public bool Combine_Shipments {
            get {
                return this.combine_ShipmentsField;
            }
            set {
                this.combine_ShipmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Combine_ShipmentsSpecified {
            get {
                return this.combine_ShipmentsFieldSpecified;
            }
            set {
                this.combine_ShipmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Reserve Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReserveSpecified {
            get {
                return this.reserveFieldSpecified;
            }
            set {
                this.reserveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Shipping_Advice Shipping_Advice {
            get {
                return this.shipping_AdviceField;
            }
            set {
                this.shipping_AdviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipping_AdviceSpecified {
            get {
                return this.shipping_AdviceFieldSpecified;
            }
            set {
                this.shipping_AdviceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Agent_Service_Code {
            get {
                return this.shipping_Agent_Service_CodeField;
            }
            set {
                this.shipping_Agent_Service_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Time {
            get {
                return this.shipping_TimeField;
            }
            set {
                this.shipping_TimeField = value;
            }
        }
        
        /// <remarks/>
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Customized_Calendar {
            get {
                return this.customized_CalendarField;
            }
            set {
                this.customized_CalendarField = value;
            }
        }
        
        /// <remarks/>
        public decimal Standard_Set_Time {
            get {
                return this.standard_Set_TimeField;
            }
            set {
                this.standard_Set_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Standard_Set_TimeSpecified {
            get {
                return this.standard_Set_TimeFieldSpecified;
            }
            set {
                this.standard_Set_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Region {
            get {
                return this.sales_RegionField;
            }
            set {
                this.sales_RegionField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Language_Code {
            get {
                return this.language_CodeField;
            }
            set {
                this.language_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Registration_No {
            get {
                return this.vAT_Registration_NoField;
            }
            set {
                this.vAT_Registration_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Submitted_By {
            get {
                return this.submitted_ByField;
            }
            set {
                this.submitted_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Submitted_Date {
            get {
                return this.submitted_DateField;
            }
            set {
                this.submitted_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Submitted_DateSpecified {
            get {
                return this.submitted_DateFieldSpecified;
            }
            set {
                this.submitted_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Verified_By {
            get {
                return this.verified_ByField;
            }
            set {
                this.verified_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Verified_Date {
            get {
                return this.verified_DateField;
            }
            set {
                this.verified_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Verified_DateSpecified {
            get {
                return this.verified_DateFieldSpecified;
            }
            set {
                this.verified_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Approved_By {
            get {
                return this.approved_ByField;
            }
            set {
                this.approved_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Approval_Date {
            get {
                return this.approval_DateField;
            }
            set {
                this.approval_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approval_DateSpecified {
            get {
                return this.approval_DateFieldSpecified;
            }
            set {
                this.approval_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Created_By {
            get {
                return this.created_ByField;
            }
            set {
                this.created_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_DateSpecified {
            get {
                return this.creation_DateFieldSpecified;
            }
            set {
                this.creation_DateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Credit_Rating {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Low_Negligible_Risk,
        
        /// <remarks/>
        High_Ordinary_Risk,
        
        /// <remarks/>
        Unacceptable_Risk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Blocked {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Ship,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Legal_Status {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Case_Ongoing,
        
        /// <remarks/>
        Case_Dismissed,
        
        /// <remarks/>
        Case_Closed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Customer_Type {
        
        /// <remarks/>
        Distributor,
        
        /// <remarks/>
        Key_Account,
        
        /// <remarks/>
        Retail,
        
        /// <remarks/>
        Staff,
        
        /// <remarks/>
        Others,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Copy_Sell_to_Addr_to_Qte_From {
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Person,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Application_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Apply_to_Oldest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Partner_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Person,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Delivery_Method {
        
        /// <remarks/>
        Own,
        
        /// <remarks/>
        Hired,
        
        /// <remarks/>
        Self_collection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Reserve {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Always,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum Shipping_Advice {
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Complete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public partial class SCMCustomers_Filter {
        
        private SCMCustomers_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public SCMCustomers_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scmcustomers")]
    public enum SCMCustomers_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Primary_Contact_No,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Area_Sales_Manager,
        
        /// <remarks/>
        Area_Sales_Rep,
        
        /// <remarks/>
        Accounts_Developer,
        
        /// <remarks/>
        Retail_Area_Manager,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Balance_LCY,
        
        /// <remarks/>
        Credit_Rating,
        
        /// <remarks/>
        Credit_Limit_LCY,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Service_Zone_Code,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        VAT_Exempt_CertNo,
        
        /// <remarks/>
        Route_Sales_Customer,
        
        /// <remarks/>
        Bad_Debtor_Status,
        
        /// <remarks/>
        Legal_Status,
        
        /// <remarks/>
        Customer_PIN,
        
        /// <remarks/>
        Customer_Type,
        
        /// <remarks/>
        Distributor,
        
        /// <remarks/>
        Transport_Route,
        
        /// <remarks/>
        Key_Account,
        
        /// <remarks/>
        Excise_Duty,
        
        /// <remarks/>
        RPM_Rate,
        
        /// <remarks/>
        Sales_Area,
        
        /// <remarks/>
        Sales_Cluster,
        
        /// <remarks/>
        Old_Customer_No,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        Bill_to_Customer_No,
        
        /// <remarks/>
        Invoice_Copies,
        
        /// <remarks/>
        Invoice_Disc_Code,
        
        /// <remarks/>
        Copy_Sell_to_Addr_to_Qte_From,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Customer_Posting_Group,
        
        /// <remarks/>
        Customer_Price_Group,
        
        /// <remarks/>
        Customer_Disc_Group,
        
        /// <remarks/>
        Allow_Line_Disc,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        Prepayment_Percent,
        
        /// <remarks/>
        Application_Method,
        
        /// <remarks/>
        Partner_Type,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Reminder_Terms_Code,
        
        /// <remarks/>
        Fin_Charge_Terms_Code,
        
        /// <remarks/>
        Cash_Flow_Payment_Terms_Code,
        
        /// <remarks/>
        Print_Statements,
        
        /// <remarks/>
        Last_Statement_No,
        
        /// <remarks/>
        Block_Payment_Tolerance,
        
        /// <remarks/>
        Preferred_Bank_Account,
        
        /// <remarks/>
        Delivery_Method,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Distance_from_Plant_KM,
        
        /// <remarks/>
        GPS_Coordinates,
        
        /// <remarks/>
        Combine_Shipments,
        
        /// <remarks/>
        Reserve,
        
        /// <remarks/>
        Shipping_Advice,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Shipping_Agent_Service_Code,
        
        /// <remarks/>
        Shipping_Time,
        
        /// <remarks/>
        Base_Calendar_Code,
        
        /// <remarks/>
        Customized_Calendar,
        
        /// <remarks/>
        Standard_Set_Time,
        
        /// <remarks/>
        Sales_Region,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        VAT_Registration_No,
        
        /// <remarks/>
        Submitted_By,
        
        /// <remarks/>
        Submitted_Date,
        
        /// <remarks/>
        Verified_By,
        
        /// <remarks/>
        Verified_Date,
        
        /// <remarks/>
        Approved_By,
        
        /// <remarks/>
        Approval_Date,
        
        /// <remarks/>
        Created_By,
        
        /// <remarks/>
        Creation_Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers SCMCustomers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers[] SCMCustomers_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers SCMCustomers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCMCustomers[] SCMCustomers_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCMCustomers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591