//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVSCMIntegrator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/SystemService")]
        public string NAVSCMIntegrator_com_olympus_zeus_SystemService {
            get {
                return ((string)(this["NAVSCMIntegrator_com_olympus_zeus_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/DynamicsNAVEmployeeCa" +
            "rd")]
        public string NAVSCMIntegrator_com_olympus_zeus_DynamicsNAVEmployeeCard_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_com_olympus_zeus_DynamicsNAVEmployeeCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/SalesItems")]
        public string NAVSCMIntegrator_com_olympus_zeus_SalesItems_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_com_olympus_zeus_SalesItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/SCMItems")]
        public string NAVSCMIntegrator_com_olympus_zeus_SCMItems_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_com_olympus_zeus_SCMItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/SCMCustomers")]
        public string NAVSCMIntegrator_SCMCustomersSVC_SCMCustomers_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_SCMCustomersSVC_SCMCustomers_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/SalesItems")]
        public string NAVSCMIntegrator_SCMProductsSVC_SalesItems_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_SCMProductsSVC_SalesItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeus.olympus.com:8817/ALMASI2016/WS/RVBL_GOLIVE/Page/NavCustomers")]
        public string NAVSCMIntegrator_NavCustomers_NavCustomers_Service {
            get {
                return ((string)(this["NAVSCMIntegrator_NavCustomers_NavCustomers_Service"]));
            }
        }
    }
}
